### ISSUE TITLE
ld: file not found: -lsigrok when installing sigrok-cli

### ISSUE THREAD

**Issue by soyeb** [rene-dev/homebrew-sigrok#10]
I have a fairly fresh brew installation on my machine.  I followed the procedure to install sigrok on the website, but when I get the step to install sigrok-cli, I get the following:

$ brew install --HEAD --with-libserialport sigrok-cli
==> Installing sigrok-cli from rene-dev/sigrok
==> Cloning git://sigrok.org/sigrok-cli
Updating /Users/soyeb/Library/Caches/Homebrew/sigrok-cli--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/sigrok-cli/HEAD
==> make install
Last 15 lines from /Users/soyeb/Library/Logs/Homebrew/sigrok-cli/03.make:
install

  CC       main.o
  CC       show.o
  CC       device.o
  CC       session.o
  CC       input.o
  CC       decode.o
  CC       parsers.o
  CC       anykey.o
  CC       options.o
  CCLD     sigrok-cli
ld: file not found: -lsigrok
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sigrok-cli] Error 1
/usr/local/Library/Homebrew/build.rb:180:in `dump': can't dump anonymous class #<Class:0x007f957d857e28> (TypeError)
	from /usr/local/Library/Homebrew/build.rb:180:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:169:in `<main>'
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Library/Homebrew/utils.rb:468:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:574:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:236:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:275:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `install'
/usr/local/Library/brew.rb:87:in `<main>'

But libsigrok is installed:

$ ls -l /usr/local/lib/libsigrok.*
lrwxr-xr-x  1 soyeb  admin  46  6 Jun 10:31 /usr/local/lib/libsigrok.3.dylib -> ../Cellar/libsigrok/HEAD/lib/libsigrok.3.dylib
lrwxr-xr-x  1 soyeb  admin  40  6 Jun 10:31 /usr/local/lib/libsigrok.a -> ../Cellar/libsigrok/HEAD/lib/libsigrok.a
lrwxr-xr-x  1 soyeb  admin  44  6 Jun 10:31 /usr/local/lib/libsigrok.dylib -> ../Cellar/libsigrok/HEAD/lib/libsigrok.dylib

and it's in my DYLD path:

$ echo $DYLD_LIBRARY_PATH
/usr/local/lib

**Comment by pldubouilh** [comment]
Might be because brew's trying to get `libsigrok` from `homebrew/science/libsigrokdecode`, and not this repo. See #11
