### ISSUE TITLE
Error compiling on Mac OS Sierra (10.12)

### ISSUE THREAD

**Issue by zhovner** [rene-dev/homebrew-sigrok#12]
Following this manual http://sigrok.org/wiki/Mac_OS_X trying to build PulseView

```
$ brew install --HEAD libserialport
$ brew install --HEAD --with-libserialport libsigrok
$ brew install --HEAD libsigrokdecode
$ brew install --HEAD --with-libserialport sigrok-cli
$ brew install --HEAD pulseview
```

On the last step `brew install --HEAD pulseview` I get:

```
3.5/include/python3.5m  -DNDEBUG   -Wall -Wextra -std=c++11 -Werror -o CMakeFiles/pulseview.dir/pv/dialogs/inputoutputoptions.cpp.o -c /tmp/pulseview-20160927-55326-3qf1fh/pv/dialogs/inputoutputoptions.cpp
/tmp/pulseview-20160927-55326-3qf1fh/pv/devices/inputfile.cpp:95:11: error: no member named 'reset' in 'sigrok::Input'
                input_->reset();
                ~~~~~~  ^
1 error generated.
make[2]: *** [CMakeFiles/pulseview.dir/pv/devices/inputfile.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [test/CMakeFiles/pulseview-test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/pulseview.dir/all] Error 2
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `dump': can't dump anonymous class #<Class:0x007fba9ea7ee90> (TypeError)
	from /usr/local/Homebrew/Library/Homebrew/build.rb:189:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `<main>'
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:495:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:605:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:260:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:286:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

Btw, there is a duplicating formulas, full tap must be choosen

```
Formulae found in multiple taps: 
$ brew install --HEAD libsigrokdecode

 * homebrew/science/libsigrokdecode
 * rene-dev/sigrok/libsigrokdecode
```

**Comment by rene-dev** [comment]
Hi,
I just updated to 10.12 and cannot reproduce your issue using the instructions in the wiki.

**Comment by cbas** [comment]
Could this be related? Not too familiar with the internals of Homebrew. 🙇 
```
brew install -vd --HEAD pulseview
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/rene-dev/homebrew-sigrok/pulseview.rb
==> Installing pulseview from rene-dev/sigrok
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/rene-dev/homebrew-sigrok/libsigrok.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libzip.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glib.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libusb.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibmm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libsigc++.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/doxygen.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf-archive.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/rene-dev/homebrew-sigrok/libsigrokdecode.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/rene-dev/homebrew-sigrok/libserialport.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:344:in `check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:310:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:134:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:127:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:277:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:160:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:160:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:160:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by samjkent** [comment]
Same issue, did you find a solution? @zhovner

**Comment by zhovner** [comment]
@samjkent no
