### ISSUE TITLE
ld: library not found for -lsigrokdecode

### ISSUE THREAD

**Issue by 1am** [rene-dev/homebrew-sigrok#6]
Hi

I've tried installing ``` brew install sigrok-cli``` today but it fails with the following error:

```
$ brew install sigrok-cli
==> Installing sigrok-cli from rene-dev/homebrew-sigrok
==> Installing sigrok-cli dependency: libsigrokdecode
==> Downloading http://sigrok.org/download/source/libsigrokdecode/libsigrokdecod
Already downloaded: /Library/Caches/Homebrew/libsigrokdecode-0.3.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/libsigrokdecode/0.3.0
==> make install
  CCLD     libsigrokdecode.la
  CCLD     tests/runtc
ld: library not found for -lsigrokdecode
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tests/runtc] Error 1
/usr/local/Library/Homebrew/build.rb:188:in `dump': can't dump anonymous class #<Class:0x007fbfc41ffcf8> (TypeError)
	from /usr/local/Library/Homebrew/build.rb:188:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:174:in `<main>'
Error: marshal data too short
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_installer.rb:499:in `load'
/usr/local/Library/Homebrew/formula_installer.rb:499:in `block in build'
/usr/local/Library/Homebrew/utils.rb:244:in `ignore_interrupts'
/usr/local/Library/Homebrew/formula_installer.rb:494:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:361:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:319:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:319:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:319:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:224:in `compute_and_install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:149:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:133:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:55:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:55:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:55:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

So i tried running ```$ brew install libsigrokdecode``` as I thought that maybe the dependency is not downloaded correctly but it seems that it fails with the same error as if the library would be a dependency of itself:

```
$ brew install libsigrokdecode
==> Installing libsigrokdecode from rene-dev/homebrew-sigrok
==> Downloading http://sigrok.org/download/source/libsigrokdecode/libsigrokdecod
Already downloaded: /Library/Caches/Homebrew/libsigrokdecode-0.3.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/libsigrokdecode/0.3.0
==> make install
  CCLD     libsigrokdecode.la
  CCLD     tests/runtc
ld: library not found for -lsigrokdecode
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tests/runtc] Error 1
/usr/local/Library/Homebrew/build.rb:188:in `dump': can't dump anonymous class #<Class:0x007f8b3c18bd38> (TypeError)
	from /usr/local/Library/Homebrew/build.rb:188:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:174:in `<main>'
Error: marshal data too short
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_installer.rb:499:in `load'
/usr/local/Library/Homebrew/formula_installer.rb:499:in `block in build'
/usr/local/Library/Homebrew/utils.rb:244:in `ignore_interrupts'
/usr/local/Library/Homebrew/formula_installer.rb:494:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:133:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:55:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:55:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:55:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

I'm using Homebrew 0.9.5 on OSX 10.10.
Is there something I'm missing in the process? It seems pretty straight forward but maybe there's some library I'd need to install?

**Comment by rene-dev** [comment]
both depend on libsigrok, which should be installed automatically, try following these instructions.
http://sigrok.org/wiki/Mac_OS_X#Building_using_Homebrew

**Comment by 1am** [comment]
This is exactly what I've followed

```
brew tap rene-dev/sigrok
brew install sigrok-cli
```

**Comment by rene-dev** [comment]
try the unstable version, I just tested it on 10.10. sigrok does not release very often.

**Comment by SaintGimp** [comment]
I'm getting the same error on both stable and unstable.

**Comment by SaintGimp** [comment]
I'm still getting the same error on stable, but unstable installs correctly (once I uninstalled libsigrok so that I could install the most recent version).
