### ISSUE TITLE
Error compiling with MacOSX Yosemite

### ISSUE THREAD

**Issue by marcams** [rene-dev/homebrew-sigrok#7]
I got the following error while compiling on MacOSX Yosemite (10.10):

==> cmake . -DENABLE_DECODE=y -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/
  CMakeLists.txt:79 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/tmp/pulseview20150703-81033-1ccga5d/CMakeFiles/CMakeOutput.log".
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Class:0x007f86d1b2ce60> (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Library/Homebrew/utils.rb:280:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:483:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:166:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:124:in `<main>'

Building it manually, I got the following errors:

MacBook:pulseview marcams$ make
[  1%] Building CXX object CMakeFiles/pulseview.dir/main.cpp.o
In file included from /Users/marcams/Documents/workspace/pulseview/main.cpp:38:
In file included from /Users/marcams/Documents/workspace/pulseview/pv/mainwindow.hpp:32:
In file included from /Users/marcams/Documents/workspace/pulseview/pv/session.hpp:38:
In file included from /opt/local/include/boost/thread.hpp:24:
In file included from /opt/local/include/boost/thread/future.hpp:38:
In file included from /opt/local/include/boost/optional.hpp:15:
/opt/local/include/boost/optional/optional.hpp:1254:53: error: unused parameter 'out'
      [-Werror,-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                    ^
/opt/local/include/boost/optional/optional.hpp:1254:95: error: unused parameter 'v'
      [-Werror,-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                                                              ^
In file included from /Users/marcams/Documents/workspace/pulseview/main.cpp:38:
In file included from /Users/marcams/Documents/workspace/pulseview/pv/mainwindow.hpp:32:
In file included from /Users/marcams/Documents/workspace/pulseview/pv/session.hpp:38:
In file included from /opt/local/include/boost/thread.hpp:24:
/opt/local/include/boost/thread/future.hpp:410:77: error: unused parameter 'lk' [-Werror,-Wunused-parameter]
            future_state::state get_state(boost::unique_lock<boost::mutex>& lk) const
                                                                            ^
3 errors generated.
make[2]: *** [CMakeFiles/pulseview.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/pulseview.dir/all] Error 2
make: *** [all] Error 2

**Comment by pagaille** [comment]
Same problem here, though I'm compiling from the git master.
Any progress on this ? Txt

**Comment by rene-dev** [comment]
Unfortunately not, I cannot reproduce this on 10.11.1, and don't have nay other system. 
are you on 10.10 as well? I cannot imaging that this is OS specific...
