### ISSUE TITLE
Cannot build pulseview

### ISSUE THREAD

**Issue by pagaille** [rene-dev/homebrew-sigrok#9]
Hi there,

I can't build pulse view on el capitan. I tried the usual troubleshooting (brew doctor, ...) but no success. Here is the command line output : 

```
$ brew install pulseview   
==> Installing pulseview from rene-dev/sigrok
==> Downloading http://sigrok.org/download/source/pulseview/pulseview-0.3.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/pulseview-0.3.0.tar.gz
==> cmake . -DENABLE_DECODE=y -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pulseview/0.3.0 -DCMAKE_BUILD_TYPE=Release -
Last 15 lines from /Users/matthieu/Library/Logs/Homebrew/pulseview/01.cmake:
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'libsigrokcxx>=0.4.0;libsigrokdecode>=0.4.0'
--   
CMake Error at /usr/local/Cellar/cmake/3.5.0/share/cmake/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.0/share/cmake/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  CMakeLists.txt:78 (kg_check_modules)



-- Configuring incomplete, errors occurred!
See also "/tmp/pulseview20160328-26833-1k4k8py/pulseview-0.3.0/CMakeFiles/CMakeOutput.log".
/usr/local/Library/Homebrew/build.rb:179:in `dump': can't dump anonymous class #<Class:0x007fd329177f60> (TypeError)
	from /usr/local/Library/Homebrew/build.rb:179:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:168:in `<main>'
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Library/Homebrew/utils.rb:437:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:572:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:231:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/brew.rb:83:in `<main>'
```

```
$ echo $PKG_CONFIG_PATH
/opt/X11/lib/pkgconfig
```

I also tried with

```
$ echo $PKG_CONFIG_PATH
/opt/X11/lib/pkgconfig:/usr/local/Cellar/libsigrok/0.4.0/lib/pkgconfig/libsigrokcxx.pc
```

Since 

```
$ pkg-config --libs libsigrokcxx
Package libsigrokcxx was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsigrokcxx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsigrokcxx' found'
```

Thanks for helping

Matthieu

**Comment by pagaille** [comment]
Still investigating. There is something wrong in the way brew tries to install things, at least on my config.

**Comment by rene-dev** [comment]
did you try to install head?
also, --debug will give you more info

**Comment by pagaille** [comment]
Thanks rene,

I succeeded. Indeed, I had to install HEAD and also had to reinstall libsigrok from your tap.

Thanks !
